# Generated by Django 5.2.10 on 2026-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
