# Generated by Django 5.2.10 on 2026-03-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0002_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_title",
                    models.CharField(max_length=200, verbose_name="电影名称"),
                ),
                (
                    "douban_url",
                    models.URLField(max_length=500, verbose_name="豆瓣链接"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("iqiyi", "爱奇艺"),
                            ("tencent", "腾讯视频"),
                            ("youku", "优酷"),
                            ("bilibili", "哔哩哔哩"),
                            ("mango", "芒果TV"),
                            ("netflix", "Netflix"),
                            ("disney", "Disney+"),
                            ("amazon", "Amazon Prime"),
                            ("other", "其他平台"),
                        ],
                        max_length=50,
                        verbose_name="视频平台",
                    ),
                ),
                (
                    "platform_url",
                    models.URLField(max_length=500, verbose_name="平台链接"),
                ),
                (
                    "vip_status",
                    models.CharField(
                        choices=[
                            ("free", "免费观看"),
                            ("vip", "VIP可看"),
                            ("pay", "付费观看"),
                            ("rent", "租赁观看"),
                        ],
                        max_length=20,
                        verbose_name="观看权限",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="价格(元)",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="画质"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(auto_now=True, verbose_name="最后检查时间"),
                ),
            ],
            options={
                "verbose_name": "视频平台链接",
                "verbose_name_plural": "视频平台链接",
                "unique_together": {("movie_title", "platform")},
            },
        ),
    ]
