# Generated by Django 5.2.10 on 2026-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0003_videoplatform"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="videoplatform",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="videoplatform",
            name="platform",
            field=models.CharField(
                choices=[
                    ("iqiyi", "爱奇艺"),
                    ("tencent", "腾讯视频"),
                    ("youku", "优酷"),
                    ("bilibili", "哔哩哔哩"),
                    ("migu", "咪咕视频"),
                    ("mango", "芒果TV"),
                    ("netflix", "Netflix"),
                    ("disney", "Disney+"),
                    ("amazon", "Amazon Prime"),
                    ("other", "其他平台"),
                ],
                max_length=50,
                verbose_name="视频平台",
            ),
        ),
        migrations.AlterField(
            model_name="videoplatform",
            name="vip_status",
            field=models.CharField(
                choices=[
                    ("free", "免费观看"),
                    ("vip", "VIP可看"),
                    ("pay", "付费观看"),
                    ("rent", "租赁观看"),
                    ("unknown", "未知"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="观看权限",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videoplatform",
            unique_together={("douban_url", "platform")},
        ),
    ]
