# Generated by Django 5.2.10 on 2026-04-16 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0004_alter_videoplatform_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["-rating", "title"],
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "评分", "verbose_name_plural": "评分"},
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.TextField(blank=True, default="", verbose_name="主演"),
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="国家/地区"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="导演"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="douban_url",
            field=models.URLField(blank=True, null=True, verbose_name="豆瓣链接"),
        ),
        migrations.AddField(
            model_name="movie",
            name="quote",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="一句话评价"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(blank=True, null=True, verbose_name="豆瓣评分"),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="评分人数"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="类型"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200, verbose_name="电影名称"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="年份"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(verbose_name="评分"),
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("user_based", "基于用户协同过滤"),
                            ("item_based", "基于物品协同过滤"),
                            ("top", "热门推荐"),
                            ("cold_start", "冷启动推荐"),
                            ("hybrid", "混合推荐"),
                            ("nl_query", "自然语言推荐"),
                        ],
                        max_length=50,
                        verbose_name="推荐算法",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="推荐分数")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="推荐理由"),
                ),
                (
                    "query_text",
                    models.TextField(blank=True, null=True, verbose_name="查询文本"),
                ),
                (
                    "clicked",
                    models.BooleanField(default=False, verbose_name="是否点击"),
                ),
                ("liked", models.BooleanField(default=False, verbose_name="是否喜欢")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="recommendation.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐日志",
                "verbose_name_plural": "推荐日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_genres",
                    models.JSONField(blank=True, default=list, verbose_name="偏好类型"),
                ),
                (
                    "favorite_countries",
                    models.JSONField(blank=True, default=list, verbose_name="偏好国家"),
                ),
                (
                    "favorite_years",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="偏好年份范围"
                    ),
                ),
                (
                    "favorite_keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="偏好关键词"
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, verbose_name="是否完成冷启动选择"
                    ),
                ),
                (
                    "profile_summary",
                    models.TextField(blank=True, null=True, verbose_name="画像总结"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户画像",
                "verbose_name_plural": "用户画像",
            },
        ),
    ]
