# Generated by Django 5.2.10 on 2026-05-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0006_moviecomment_moviefeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviecomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "电影评论",
                "verbose_name_plural": "电影评论",
            },
        ),
        migrations.AddField(
            model_name="moviecomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="recommendation.moviecomment",
                verbose_name="父评论",
            ),
        ),
    ]
