# Generated by Django 5.2.10 on 2026-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0007_alter_moviecomment_options_moviecomment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="public_favorites",
            field=models.BooleanField(default=False, verbose_name="是否公开收藏夹"),
        ),
    ]
