# Generated by Django 5.2.10 on 2026-05-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendation",
            "0009_discussionpost_discussionreply_discussiontopic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community/", verbose_name="配图"
            ),
        ),
    ]
