# Generated by Django 5.2.10 on 2026-05-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0010_discussionpost_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="片单标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="片单描述"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collections/",
                        verbose_name="封面图",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开"),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("movie_count", models.IntegerField(default=0, verbose_name="电影数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "电影片单",
                "verbose_name_plural": "电影片单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="推荐语"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="recommendation.movie",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="recommendation.moviecollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "片单电影",
                "verbose_name_plural": "片单电影",
                "ordering": ["order", "-added_at"],
                "unique_together": {("collection", "movie")},
            },
        ),
    ]
