# Generated by Django 5.2.10 on 2026-05-14 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0012_collectioncomment_collectionlike"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectioncomment",
            options={
                "ordering": ["-like_count", "-created_at"],
                "verbose_name": "片单评论",
                "verbose_name_plural": "片单评论",
            },
        ),
        migrations.AddField(
            model_name="collectioncomment",
            name="dislike_count",
            field=models.IntegerField(default=0, verbose_name="拉踩数"),
        ),
        migrations.AddField(
            model_name="collectioncomment",
            name="like_count",
            field=models.IntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="collectioncomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="recommendation.collectioncomment",
            ),
        ),
        migrations.CreateModel(
            name="CollectionCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("like", "点赞"), ("dislike", "拉踩")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="recommendation.collectioncomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cc_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "评论反馈",
                "verbose_name_plural": "评论反馈",
                "unique_together": {("comment", "user")},
            },
        ),
    ]
